services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    container_name: fastapi_model_api
    ports:
      - "8000:8000"

  web:
    build:
      context: ./app
    container_name: streamlit_web_app
    ports:
      - "8501:8501"
    depends_on:
      - api
